export default {
    title: 'dark',
    colors: {
        statusBar: 'light',
        main: '#00BFFF',
        background: '#333',
        division: '#A0A0A0',
        secondaryDivision: 'rgba(160, 160, 160, 0.2)',
        strongText: '#FFF',
        lightText: '#AAA',
        profileExperienceIcon: '#FBD513',
        profileMoneyIcon: '#00D200',
        defaultBadgeBackground: '#FAFA00',
        defaultBadgeBorder: '#E5E500',
        defaultBadgeIcon: '#A0A000',
        lightDefaultProfileIcon: '#AAA',
        strongDefaultProfileIcon: '#FFF',
        imageBadgeQuantityBackground: 'rgba(0, 0, 0, 0.5)',
        imageBadgeQuantityText: '#FFF',
        tabIconActive: '#00BFFF',
        tabIconInactive: '#AAA',
        tabButtonActiveBackground: '#222',
        tabButtonInactiveBackground: '#333',
        tabButtonDivision: '#222',
        signOutButtonBackground: '#FF0000',
        signOutButtonText: '#FFF',
        signOutButtonRipple: 'rgba(0, 0, 0, 0.2)',
        lectureButtonMainStroke: '#00BFFF' ,
        lectureButtonSecondaryStroke: '#AAA',
        lectureButtonDisabledStroke: '#AAA',
        lectureButtonCompletedStroke: '#F7F704',
        lectureButtonLevelBackground: '#00BFFF',
        lectureButtonLevelText: '#FFF',
        lectureButtonCompletedLevelText: '#222',
        lectureButtonRipple: '#FFF',
        textInputBackground: '#FFF',
        textInputPlaceholder: '#000',
        primaryButtonBackground: '#00BFFF',
        primaryButtonRipple: 'rgba(0, 0, 0, 0.2)',
        primaryButtonText: '#FFF',
        borderlessButtonRipple: '#FFF',
        answerIndicatorBorder: '#AAA',
        correctAnswerIndicatorBackground: 'rgba(30, 252, 30, 1)',
        incorrectAnswerIndicatorBackground: '#FF0000',
        undefinedAnswerIndicatorBackground: '#666',
        questionMediaBorder: '#A0A0A0',
        lectureCompletionIconBackground: '#A0A0A0',
        lectureCompletionIcon: '#F7F704',

        white: '#FFF'
    }
}