export default {
    title: 'light',
    colors: {
        statusBar: 'dark',
        main: '#00BFFF',
        background: '#FFF',
        division: 'rgba(0, 0, 0, 0.1)',
        secondaryDivision: 'rgba(0, 0, 0, 0.05)',
        strongText: '#444442',
        lightText: '#828282',
        profileExperienceIcon: '#FBD513',
        profileMoneyIcon: '#00D200',
        defaultBadgeBackground: '#FAFA00',
        defaultBadgeBorder: '#E5E500',
        defaultBadgeIcon: '#A0A000',
        lightDefaultProfileIcon: '#AAA',
        strongDefaultProfileIcon: '#FFF',
        imageBadgeQuantityBackground: 'rgba(0, 0, 0, 0.5)',
        imageBadgeQuantityText: '#FFF',
        tabIconActive: '#00BFFF',
        tabIconInactive: 'rgba(0, 0, 0, 0.5)',
        tabButtonActiveBackground: 'rgba(0, 0, 0, 0.1)',
        tabButtonInactiveBackground: '#FFF',
        tabButtonDivision: 'rgba(0, 0, 0, 0.1)',
        signOutButtonBackground: '#FF0000',
        signOutButtonText: '#FFF',
        signOutButtonRipple: 'rgba(0, 0, 0, 0.2)',
        lectureButtonMainStroke: '#00BFFF',
        lectureButtonSecondaryStroke: 'rgba(0, 0, 0, 0.2)',
        lectureButtonDisabledStroke: '#777',
        lectureButtonCompletedStroke: '#F7F704',
        lectureButtonLevelBackground: '#00BFFF',
        lectureButtonLevelText: '#FFF',
        lectureButtonCompletedLevelText: '#222',
        lectureButtonRipple: 'rgba(0, 0, 0, 0.2)',
        textInputBackground: '#FFF',
        textInputPlaceholder: 'rgba(0, 0, 0, 0.4)',
        primaryButtonBackground: '#00BFFF',
        primaryButtonRipple: 'rgba(0, 0, 0, 0.2)',
        primaryButtonText: '#FFF',
        borderlessButtonRipple: 'rgba(0, 0, 0, 0.2)',
        answerIndicatorBorder: 'rgba(0, 0, 0, 0.25)',
        correctAnswerIndicatorBackground: 'rgba(30, 252, 30, 1)',
        incorrectAnswerIndicatorBackground: '#FF0000',
        undefinedAnswerIndicatorBackground: 'rgba(0, 0, 0, 0.1)',
        questionMediaBorder: '#444442',
        lectureCompletionIconBackground: '#444442',
        lectureCompletionIcon: '#F7F704',
        themeSwitchThumbOn: '#f5dd4b',
        themeSwitchThumbOff: '#e4e3e4',
        themeSwitchTrackOn: '#81b0ff',
        themeSwitchTrackOff: '#555',

        white: '#FFF'
    }
}